### ISSUE TITLE
Add method to test for support

### ISSUE THREAD

**Issue by tremby** [feross/clipboard-copy#11]
It'd be useful to add a method which returns whether there is support or not in the current browser.

**Comment by tremby** [comment]
If the docs I'm reading are correct, it could be as simple as `document.queryCommandSupported('copy') && document.queryCommandEnabled('copy')` if the support target is only newer browsers.

**Comment by tremby** [comment]
In fact for it to work as expected when a user input hasn't just been performed, I think this is better as just `document.queryCommandSupported('copy')`.

**Comment by feross** [comment]
We already return a boolean that indicates whether the copy worked or not. I updated the docs to indicate that.

**Comment by tremby** [comment]
Well sure, but what if you want to know before even trying? I'd commonly want to present a different UI if I know it's not possible to copy something to clipboard.

**Comment by LinusU** [comment]
Kind of liked this idea, PR up in #14
