### ISSUE TITLE
Copy not working on non-https dev server

### ISSUE THREAD

**Issue by gfx** [feross/clipboard-copy#32]
I use lookpack domains, e.g. `lvh.me`, to develop my web service because it uses subdomains.

As https://developers.google.com/web/updates/2018/03/clipboardapi says, however, `navigator.clipboard` only works on https; otherwise, it throws `undefined` as permission denied.

It will be nice if the module fallbacks to `execCommand("copy")` when `witeText()` fails.

**Comment by feross** [comment]
This is fixed in 3.0.0
