### ISSUE TITLE
Unhandled Promise Rejection: undefined

### ISSUE THREAD

**Issue by pszh** [feross/clipboard-copy#34]
在 safri上出现这个错误。。。。

**Comment by pszh** [comment]
have error in safari   ，Unhandled Promise Rejection: undefined

**Comment by matthieu80** [comment]
Hi @feross 
Thank you for this module, very useful!
I currently have the same error than described above.
I am on version 12.1 of safari

**Comment by JoeDuncko** [comment]
Having the same issue

**Comment by joschka** [comment]
I tested 3.0.0 with Browserstack on Safari 12.1 (Mojave) today and cannot reproduce the error. Seems to work fine.

**Comment by feross** [comment]
Works for me on Safari 12.1.2. If you are having an issue, you will need to provide more details or submit a pull request that fixes the issue.
