### ISSUE TITLE
DOMException is not supported by Edge

### ISSUE THREAD

**Issue by stud-mai** [feross/clipboard-copy#43]
Returning promise rejection with 'The request is not allowed' error is failed in Edge browser (v17) with error message in console `Function expected`.
For information see following:
- https://caniuse.com/#feat=mdn-api_domexception_domexception
- https://developer.mozilla.org/en-US/docs/Web/API/DOMException (Browser compatibility chapter)

**Comment by feross** [comment]
Thanks for opening this issue. We only support the last two releases of evergreen browsers like Edge, so we don't support v17.
